apiVersion: kallucinate.io/v1
kind: Kallucinate
metadata:
  labels:
    app.kubernetes.io/name: kallucination
    app.kubernetes.io/managed-by: kustomize
  name: kallucinate-sample
spec:
  # TODO(user): Add fields here
